### ISSUE TITLE
Supporting custom parameters

### ISSUE THREAD

**Issue by ElMassimo** [antfu/vite-plugin-glob#2]
The current proposal mentions support for a [custom query](https://github.com/antfu/vite-plugin-glob#custom-query).

I'm wondering if we could make that a bit more idiomatic for URLs that have custom parameters, such as in:

- [`imagetools`](https://github.com/JonasKruckenberg/imagetools)
- [`vite-plugin-image-presets`](https://github.com/ElMassimo/vite-plugin-image-presets)

For example, as in [this type of use case](https://github.com/ElMassimo/vite-plugin-image-presets/discussions/6):

```ts
const images = import.meta.importGlob('./dir/*.jpg', { query: { preset: 'full' } })

/* {
  './dir/foo.jpg': () => import('./dir/foo.jpg?preset=full'),
  './dir/bar.jpg': () => import('./dir/bar.jpg?preset=full'),
} */
```

**Comment by antfu** [comment]
Yeah sounds like a good idea. Want to work on a PR for this?

The `as` syntax is to align https://github.com/tc39/proposal-import-reflection in the future (we might use it for static import in v3.0 instead of the query). But for now, I think `query` sounds like a more natural solution (we could throw an error ensure there is no `as` and `query	` exist at the same time.

**Comment by antfu** [comment]
Working in it :P

**Comment by ElMassimo** [comment]
Haha, you are too fast, I just woke up 😄
